import cv2
import numpy as np
img=cv2.imread("output images/grayscale.jpg")
sobel_x=cv2.Sobel(img,cv2.CV_64F,1,0,3)
sobel_y=cv2.Sobel(img,cv2.CV_64F,0,1,3)
laplacian=cv2.Laplacian(img,cv2.CV_64F)
blur=cv2.GaussianBlur(img,(9,9),0)
canny=cv2.Canny(blur,100,200)
sobel_x=cv2.convertScaleAbs(sobel_x)
sobel_y=cv2.convertScaleAbs(sobel_y)
laplacian=cv2.convertScaleAbs(laplacian)
canny=cv2.convertScaleAbs(canny)
cv2.imshow("Original",img)
cv2.imshow("Sobel_X",sobel_x)
cv2.imshow("Sobel_Y",sobel_y)
cv2.imshow("Laplacian",laplacian)
cv2.imshow("Canny",canny)
cv2.waitKey(0)
cv2.destroyAllWindows()